IMAGE = "debian/bookworm64"
MEMORY = "1024"
CPUS = 1

Vagrant.configure("2") do |config|
	server.vm.box = IMAGE
	server.vm.network "private_network", ip: "192.168.56.110"
	server.vm.hostname = "cpaluszeS"
	server.vm.synced_folder ".", "/vagrant"
	server.vm.provider "virtualbox" do |vb|
		vb.memory = MEMORY
		vb.cpus = CPUS
		vb.name = "cpaluszeS"
	end
	server.vm.provision "shell", path: "./setup_server.sh"
end
