IMAGE = "debian/bookworm64"
MEMORY = "2048"
CPUS = 2

Vagrant.configure("2") do |config|
	config.vm.box = IMAGE
	config.vm.network "private_network", ip: "192.168.56.110"
	config.vm.hostname = "cpaluszeS"
	config.vm.synced_folder ".", "/vagrant"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = MEMORY
		vb.cpus = CPUS
		vb.name = "cpaluszeS"
	end
	config.vm.provision "shell", path: "./setup_server.sh"
end
