Vagrant.configure("2") do |config|
	# Latest stable debian version: 12 Bookworm
	config.vm.box = "debian/bookworm64"
	
	# TODO: set network settings	
	# TODO: set hostname	
	# TODO: set machine resources
	# config.vm.provider "virtualbox" do |vb|
	#   # Display the VirtualBox GUI when booting the machine
	#   vb.gui = true
	#
	#   # Customize the amount of memory on the VM:
	#   vb.memory = "1024"
	# end
end
