Vagrant.configure("2") do |config|
	# Latest stable debian version: 12 Bookworm
	config.vm.box = "debian/bookworm64"

	# TODO: set network settings

	# TODO: set hostname

	# set machine resources
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
		vb.name = "cpaluszeS"
	end
end
