Vagrant.configure("2") do |config|
	config.vm.define "Server" do |server|
		# Latest stable debian version: 12 Bookworm
		server.vm.box = "debian/bookworm64"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.hostname = "cpaluszeS"
		server.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "cpaluszeS"
		end
		server.vm.provision "shell", path: "./setup_server.sh"
	end

	config.vm.define "Worker" do |worker|
		worker.vm.box = "debian/bookworm64"
		worker.vm.network "private_network", ip: "192.168.56.111"
		worker.vm.hostname = "cpaluszeSW"
		worker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
			vb.cpus = 1
			vb.name = "cpaluszeSW"
		end
		worker.vm.provision "shell", path: "./setup_worker.sh"
	end
end
